In [17]:
import pandas as pd
import numpy as np
import os

In [28]:
Data = pd.read_csv('/Users/tracy/Desktop/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/NumEmp/AggregateYearlyData.wide.csv')
Data

,Occupations,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Management occupations,555152.00,538868.00,603437.500,629771.250,685725.250,710697.5,738015.00,727781.000,693368.5,748540.5
1,Business and financial operations occupations,341867.25,347058.25,348813.625,370954.750,374852.500,378538.5,381351.25,408266.125,419721.5,437783.5
2,Computer and mathematical occupations,129836.25,129610.25,145511.250,158481.875,157821.625,166344.0,182507.25,184616.250,212220.0,212493.0
3,Architecture and engineering occupations,54226.25,62655.25,57477.000,51836.625,62845.375,61046.5,68765.25,69674.500,68106.5,75378.5
4,"Life, physical, and social science occupations",50566.50,56399.50,52814.250,50389.625,53213.125,61940.0,58716.50,56667.250,64962.0,61886.0
5,Community and social service occupations,122973.00,104616.00,116521.375,124456.625,120567.625,125916.5,133204.00,138300.875,115189.5,133721.5
6,Legal occupations,139558.25,145403.25,145999.875,133874.125,140116.875,149847.0,150222.25,144387.875,141583.0,147392.0
7,"Education, training, and library occupations",398378.00,386141.00,409996.250,425314.375,433337.375,448925.0,415227.00,428639.250,452035.0,459713.0
8,"Arts, design, entertainment, sports, and media...",297418.00,314854.00,322478.500,348746.250,326988.250,346099.5,347484.00,368612.000,355466.5,349345.5
9,Health diagnosing and treating practitioners a...,198486.50,194109.50,213491.125,218173.750,222505.250,226249.5,236781.50,239778.625,235305.5,241476.5
10,Health technologists and technicians,66799.00,68263.00,69781.125,68170.500,81922.500,91912.0,79291.00,92955.125,86006.0,88458.0
11,Healthcare support occupations,253999.00,257936.00,260978.750,275692.625,261548.625,271790.5,283578.00,301163.250,351295.5,370240.5
12,"Fire fighting and prevention, and other protec...",104832.50,109542.50,111721.625,107395.250,101078.750,106526.5,104377.50,107292.125,109167.5,120083.5
13,Law enforcement workers including supervisors,57374.25,54686.25,60926.000,55362.125,57527.875,58624.5,57021.25,62573.500,60818.5,61299.5
14,Food preparation and serving related occupations,336968.75,376449.75,367739.000,371458.250,398292.500,413959.0,398791.75,384540.000,377419.0,387215.0
15,Building and grounds cleaning and maintenance ...,299408.00,294417.00,287872.125,317784.500,310608.500,298689.5,297485.00,304999.625,297937.5,280558.5
16,Personal care and service occupations,274269.25,296898.25,295994.875,289360.500,302526.250,308635.5,331687.25,323892.375,261423.5,253862.5
17,Sales and related occupations,621491.25,659189.25,661007.375,652067.750,652031.500,639599.0,658210.25,627175.375,592583.0,605927.0
18,Office and administrative support occupations,779811.50,776806.50,778614.625,768034.125,767100.625,790438.5,773342.50,797758.125,703787.5,634458.5
19,"Farming, fishing, and forestry occupations",3604.00,8709.00,4098.125,4093.000,4364.000,6223.0,3749.00,5453.125,3162.0,5190.0
20,Construction and extraction occupations,276049.50,275838.50,274084.000,277003.000,298331.500,293826.5,288614.50,306867.500,310193.5,303427.5
21,"Installation, maintenance, and repair occupations",111808.25,114664.25,112345.125,127171.375,114496.125,123636.5,122622.25,115965.625,95279.5,110389.5
22,Production occupations,193545.50,180604.50,187946.750,170748.250,170006.750,171431.5,157550.50,158939.250,150561.5,149535.5
23,Transportation occupations,240034.50,235066.50,257435.875,251799.500,280691.000,288061.0,295728.50,293206.875,305408.0,282836.0
24,Material moving occupations,102361.25,87665.25,95917.625,94607.875,90894.625,83841.5,82524.25,100902.125,134941.5,132797.5

In [29]:
Data.index.values
Years = [i for i in range(1,10)]

def add_variance(Years_data):
    variance = 0
    for year in Years:
        variance_temp = abs(Years_data[year+1] - Years_data[year])
        if (variance_temp > variance):
            variance = variance_temp
    return variance

Data['range'] = Data.apply(add_variance,axis = 1)
Data['range_pct'] = Data['range']/((Data["2010"] + Data["2011"] + Data["2012"] + Data["2013"] + Data["2014"] + Data["2015"] + Data["2016"] + Data["2017"] + Data["2018"] + Data["2019"])/10)
Data = Data.iloc[:,[0,11,12]]
Data

                                          Occupations      range  range_pct
0                              Management occupations  64569.500   0.097370
1       Business and financial operations occupations  26914.875   0.070657
2               Computer and mathematical occupations  27603.750   0.164363
3            Architecture and engineering occupations  11008.750   0.174186
4      Life, physical, and social science occupations   8726.875   0.153763
5            Community and social service occupations  23111.375   0.187066
6                                   Legal occupations  12125.750   0.084301
7        Education, training, and library occupations  33698.000   0.079146
8   Arts, design, entertainment, sports, and media...  26267.750   0.077773
9   Health diagnosing and treating practitioners a...  19381.625   0.087055
10               Health technologists and technicians  13752.000   0.173295
11                     Healthcare support occupations  50132.250   0.173575
12  Fire fighting and prevention, and other protec...  10916.000   0.100886
13      Law enforcement workers including supervisors   6239.750   0.106442
14   Food preparation and serving related occupations  39481.000   0.103548
15  Building and grounds cleaning and maintenance ...  29912.375   0.100049
16              Personal care and service occupations  62468.875   0.212584
17                      Sales and related occupations  37698.000   0.059187
18      Office and administrative support occupations  93970.625   0.124133
19         Farming, fishing, and forestry occupations   5105.000   1.049434
20            Construction and extraction occupations  21328.500   0.073439
21  Installation, maintenance, and repair occupations  20686.125   0.180133
22                             Production occupations  17198.500   0.101714
23                         Transportation occupations  28891.500   0.105819
24                        Material moving occupations  34039.375   0.338211

In [30]:
Data.to_csv(r"/Users/tracy/Desktop/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/NumEmp/Occupation_Yearly_withRange.csv",index = False)