In [1]:
import numpy as np
import pandas as pd
import os

In [7]:
YearlyNumEmps = pd.read_csv('C:/Users/eabea/Dropbox/Documents/STAT W5702/Project/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/NumEmp/Occupation_Yearly.csv')
AvgEmpsByOcc = pd.read_csv('C:/Users/eabea/Dropbox/Documents/STAT W5702/Project/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/NumEmp/AverageEmpsByOccupation.csv')

YearlyNumEmps = YearlyNumEmps.drop(columns = ['Unnamed: 0'])
AvgEmpsByOcc = AvgEmpsByOcc.drop(columns = ['Unnamed: 0'])

In [8]:
YearlyNumEmps.style

In [9]:
AvgEmpsByOcc.style

In [23]:
Occupations = [AvgEmpsByOcc.iloc[i][0] for i in range(len(AvgEmpsByOcc))]
Avg = []

for i in range(len(YearlyNumEmps)):
    for x in range(len(Occupations)):
        if Occupations[x] == YearlyNumEmps.iloc[i][0]:
            Avg.append(AvgEmpsByOcc.iloc[x][1])
            
    
YearlyNumEmps['AvgEmp'] = Avg
YearlyNumEmps['Normalized'] = YearlyNumEmps['YearlyNumEmp'] / YearlyNumEmps['AvgEmp']

In [25]:
YearlyNumEmps.to_csv(os.path.join('C:/Users/eabea/Dropbox/Documents/STAT W5702/Project/STAT5702_NYC_Employment_Analysis/DataPreprocessing/Data/NumEmp/','YearlyNumEmpsWithNorm.csv'),index = False)