In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
Asian_Alone2010 = pd.read_csv(r"./2010_Asian_Alone.csv")
Asian_Alone2011 = pd.read_csv(r"./2011_Asian_Alone.csv")
Asian_Alone2012 = pd.read_csv(r"./2012_Asian_Alone.csv")
Asian_Alone2013 = pd.read_csv(r"./2013_Asian_Alone.csv")
Asian_Alone2014 = pd.read_csv(r"./2014_Asian_Alone.csv")
Asian_Alone2015 = pd.read_csv(r"./2015_Asian_Alone.csv")
Asian_Alone2016 = pd.read_csv(r"./2016_Asian_Alone.csv")
Asian_Alone2017 = pd.read_csv(r"./2017_Asian_Alone.csv")
Asian_Alone2018 = pd.read_csv(r"./2018_Asian_Alone.csv")
Asian_Alone2019 = pd.read_csv(r"./2019_Asian_Alone.csv")

In [6]:
Asian_Alone2010["year"] = Asian_Alone2010.apply(lambda x: 2010, axis=1)
Asian_Alone2010["race"] = Asian_Alone2010.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2010.loc[2:36, "Label"] += "_Male"
Asian_Alone2010.loc[37:72, "Label"] += "_Female"
Asian_Alone2011["year"] = Asian_Alone2011.apply(lambda x: 2011, axis=1)
Asian_Alone2011["race"] = Asian_Alone2011.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2011.loc[2:36, "Label"] += "_Male"
Asian_Alone2011.loc[37:72, "Label"] += "_Female"
Asian_Alone2012["year"] = Asian_Alone2012.apply(lambda x: 2012, axis=1)
Asian_Alone2012["race"] = Asian_Alone2012.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2012.loc[2:36, "Label"] += "_Male"
Asian_Alone2012.loc[37:72, "Label"] += "_Female"
Asian_Alone2013["year"] = Asian_Alone2013.apply(lambda x: 2013, axis=1)
Asian_Alone2013["race"] = Asian_Alone2013.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2013.loc[2:36, "Label"] += "_Male"
Asian_Alone2013.loc[37:72, "Label"] += "_Female"
Asian_Alone2014["year"] = Asian_Alone2014.apply(lambda x: 2014, axis=1)
Asian_Alone2014["race"] = Asian_Alone2014.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2014.loc[2:36, "Label"] += "_Male"
Asian_Alone2014.loc[37:72, "Label"] += "_Female"
Asian_Alone2015["year"] = Asian_Alone2015.apply(lambda x: 2015, axis=1)
Asian_Alone2015["race"] = Asian_Alone2015.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2015.loc[2:36, "Label"] += "_Male"
Asian_Alone2015.loc[37:72, "Label"] += "_Female"
Asian_Alone2016["year"] = Asian_Alone2016.apply(lambda x: 2016, axis=1)
Asian_Alone2016["race"] = Asian_Alone2016.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2016.loc[2:36, "Label"] += "_Male"
Asian_Alone2016.loc[37:72, "Label"] += "_Female"
Asian_Alone2017["year"] = Asian_Alone2017.apply(lambda x: 2017, axis=1)
Asian_Alone2017["race"] = Asian_Alone2017.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2017.loc[2:36, "Label"] += "_Male"
Asian_Alone2017.loc[37:72, "Label"] += "_Female"
Asian_Alone2018["year"] = Asian_Alone2018.apply(lambda x: 2018, axis=1)
Asian_Alone2018["race"] = Asian_Alone2018.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2018.loc[2:36, "Label"] += "_Male"
Asian_Alone2018.loc[37:72, "Label"] += "_Female"
Asian_Alone2019["year"] = Asian_Alone2019.apply(lambda x: 2019, axis=1)
Asian_Alone2019["race"] = Asian_Alone2019.apply(lambda x: "Asian Alone", axis=1)
Asian_Alone2019.loc[2:36, "Label"] += "_Male"
Asian_Alone2019.loc[37:72, "Label"] += "_Female"
frames = [Asian_Alone2010,Asian_Alone2011,Asian_Alone2012,Asian_Alone2013,Asian_Alone2014,Asian_Alone2015,Asian_Alone2016,Asian_Alone2017,Asian_Alone2018,Asian_Alone2019]
Asian_Alone = pd.concat(frames)
Asian_Alone = Asian_Alone.rename(columns={"Bronx County, New York / Estimate":"Bronx County, New York",
                                          "Kings County, New York / Estimate":"Kings County, New York",
                                          "New York County, New York / Estimate":"New York County, New York",
                                          "Queens County, New York / Estimate":"Queens County, New York",
                                          "Richmond County, New York / Estimate":"Richmond County, New York"})

Asian_Alone

,Label,"Bronx County, New York","Kings County, New York","New York County, New York","Queens County, New York","Richmond County, New York",year,race
0,Total:,22160,121664,98647,248187,16530.0,2010,Asian Alone
1,Male:,12283,66638,44989,135390,8822.0,2010,Asian Alone
2,"Management, business, science, and arts occupa...",3201,15689,28593,41250,4012.0,2010,Asian Alone
3,"Management, business, and financial occupation...",1103,5399,12780,19782,1419.0,2010,Asian Alone
4,Management occupations_Male_Male_Male,458,3330,7144,11371,719.0,2010,Asian Alone
...,...,...,...,...,...,...,...,...
68,"Installation, maintenance, and repair occupati...",0,99,0,0,204.0,2019,Asian Alone
69,"Production, transportation, and material movin...",606,3590,796,6487,264.0,2019,Asian Alone
70,Production occupations_Female_Female_Female,535,2350,586,4524,126.0,2019,Asian Alone
71,Transportation occupations_Female_Female_Female,71,602,0,827,0.0,2019,Asian Alone
72,Material moving occupations_Female_Female_Female,0,638,210,1136,138.0,2019,Asian Alone

In [21]:
Asian_Alone.to_csv(r"./Asian_Alone.csv")

In [69]:
BLACK_OR_AFRICAN_AMERICAN_ALONE2010 = pd.read_csv(r"./2010_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")
BLACK_OR_AFRICAN_AMERICAN_ALONE2011 = pd.read_csv(r"./2011_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")
BLACK_OR_AFRICAN_AMERICAN_ALONE2012 = pd.read_csv(r"./2012_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")
BLACK_OR_AFRICAN_AMERICAN_ALONE2013 = pd.read_csv(r"./2013_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")
BLACK_OR_AFRICAN_AMERICAN_ALONE2014 = pd.read_csv(r"./2014_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")
BLACK_OR_AFRICAN_AMERICAN_ALONE2015 = pd.read_csv(r"./2015_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")
BLACK_OR_AFRICAN_AMERICAN_ALONE2016 = pd.read_csv(r"./2016_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")
BLACK_OR_AFRICAN_AMERICAN_ALONE2017 = pd.read_csv(r"./2017_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")
BLACK_OR_AFRICAN_AMERICAN_ALONE2018 = pd.read_csv(r"./2018_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")
BLACK_OR_AFRICAN_AMERICAN_ALONE2019 = pd.read_csv(r"./2019_BLACK_OR_AFRICAN_AMERICAN_ALONE.csv")

In [70]:
BLACK_OR_AFRICAN_AMERICAN_ALONE2010["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2010.apply(lambda x: 2010, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2010["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2010.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2010.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2010.loc[37:72, "Label"] += "_Female"
BLACK_OR_AFRICAN_AMERICAN_ALONE2011["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2011.apply(lambda x: 2011, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2011["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2011.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2011.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2011.loc[37:72, "Label"] += "_Female"
BLACK_OR_AFRICAN_AMERICAN_ALONE2012["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2012.apply(lambda x: 2012, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2012["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2012.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2012.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2012.loc[37:72, "Label"] += "_Female"
BLACK_OR_AFRICAN_AMERICAN_ALONE2013["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2013.apply(lambda x: 2013, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2013["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2013.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2013.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2013.loc[37:72, "Label"] += "_Female"
BLACK_OR_AFRICAN_AMERICAN_ALONE2014["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2014.apply(lambda x: 2014, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2014["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2014.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2014.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2014.loc[37:72, "Label"] += "_Female"
BLACK_OR_AFRICAN_AMERICAN_ALONE2015["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2015.apply(lambda x: 2015, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2015["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2015.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2015.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2015.loc[37:72, "Label"] += "_Female"
BLACK_OR_AFRICAN_AMERICAN_ALONE2016["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2016.apply(lambda x: 2016, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2016["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2016.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2016.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2016.loc[37:72, "Label"] += "_Female"
BLACK_OR_AFRICAN_AMERICAN_ALONE2017["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2017.apply(lambda x: 2017, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2017["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2017.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2017.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2017.loc[37:72, "Label"] += "_Female"
BLACK_OR_AFRICAN_AMERICAN_ALONE2018["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2018.apply(lambda x: 2018, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2018["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2018.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2018.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2018.loc[37:72, "Label"] += "_Female"
BLACK_OR_AFRICAN_AMERICAN_ALONE2019["year"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2019.apply(lambda x: 2019, axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2019["race"] = BLACK_OR_AFRICAN_AMERICAN_ALONE2019.apply(lambda x: "BLACK OR AFRICAN AMERICAN ALONE", axis=1)
BLACK_OR_AFRICAN_AMERICAN_ALONE2019.loc[2:36, "Label"] += "_Male"
BLACK_OR_AFRICAN_AMERICAN_ALONE2019.loc[37:72, "Label"] += "_Female"
frames = [BLACK_OR_AFRICAN_AMERICAN_ALONE2010,BLACK_OR_AFRICAN_AMERICAN_ALONE2011,BLACK_OR_AFRICAN_AMERICAN_ALONE2012,
          BLACK_OR_AFRICAN_AMERICAN_ALONE2013,BLACK_OR_AFRICAN_AMERICAN_ALONE2014,BLACK_OR_AFRICAN_AMERICAN_ALONE2015,
          BLACK_OR_AFRICAN_AMERICAN_ALONE2016,BLACK_OR_AFRICAN_AMERICAN_ALONE2017,BLACK_OR_AFRICAN_AMERICAN_ALONE2018,
          BLACK_OR_AFRICAN_AMERICAN_ALONE2019]
BLACK_OR_AFRICAN_AMERICAN_ALONE = pd.concat(frames)
BLACK_OR_AFRICAN_AMERICAN_ALONE = BLACK_OR_AFRICAN_AMERICAN_ALONE.rename(columns={"Bronx County, New York / Estimate":"Bronx County, New York",
                                                                                  "Kings County, New York / Estimate":"Kings County, New York",
                                                                                  "New York County, New York / Estimate":"New York County, New York",
                                                                                  "Queens County, New York / Estimate":"Queens County, New York",
                                                                                  "Richmond County, New York / Estimate":"Richmond County, New York"})
BLACK_OR_AFRICAN_AMERICAN_ALONE

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:45: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,"Bronx County, New York","Kings County, New York",Label,"New York County, New York","Queens County, New York","Richmond County, New York",race,year
0,183071,362635,Total:,93376,183443,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
1,77153,149278,Male:,44349,81639,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
2,15701,33765,"Management, business, science, and arts occupa...",14457,16550,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
3,5947,12398,"Management, business, and financial occupation...",5690,6039,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
4,3512,8521,Management occupations_Male,3004,3973,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
5,2435,3877,Business and financial operations occupations_...,2686,2066,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
6,2587,4195,"Computer, engineering, and science occupations...",1552,2665,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
7,1493,1861,Computer and mathematical occupations_Male,988,1789,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
8,818,2069,Architecture and engineering occupations_Male,73,637,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
9,276,265,"Life, physical, and social science occupations...",491,239,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
10,5858,12735,"Education, legal, community service, arts, and...",6533,6381,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
11,2212,4280,Community and social service occupations_Male,1033,2890,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
12,541,1679,Legal occupations_Male,787,571,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
13,2445,3760,"Education, training, and library occupations_Male",1481,1388,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
14,660,3016,"Arts, design, entertainment, sports, and media...",3232,1532,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
15,1309,4437,Healthcare practitioners and technical occupat...,682,1465,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
16,728,2074,Health diagnosing and treating practitioners a...,470,928,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
17,581,2363,Health technologists and technicians_Male,212,537,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
18,20893,37388,Service occupations:_Male,9326,20706,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
19,2338,2849,Healthcare support occupations_Male,431,1839,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
20,7409,13125,Protective service occupations:_Male,2558,7873,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
21,6510,10282,"Fire fighting and prevention, and other protec...",1788,5552,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
22,899,2843,Law enforcement workers including supervisors_...,770,2321,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
23,2521,6490,Food preparation and serving related occupatio...,2056,3742,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
24,6778,11007,Building and grounds cleaning and maintenance ...,2979,4326,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
25,1847,3917,Personal care and service occupations_Male,1302,2926,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
26,14387,30824,Sales and office occupations:_Male,9452,17305,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
27,6168,14931,Sales and related occupations_Male,3462,7233,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
28,8219,15893,Office and administrative support occupations_...,5990,10072,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
29,11430,20782,"Natural resources, construction, and maintenan...",3258,10669,NaN,BLACK OR AFRICAN AMERICAN ALONE,2010
...,...,...,...,...,...,...,...,...
43,1045,2445,Computer and mathematical occupations_Female,1741,1670,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
44,381,603,Architecture and engineering occupations_Female,0,333,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
45,184,919,"Life, physical, and social science occupations...",132,100,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
46,14328,36098,"Education, legal, community service, arts, and...",11609,19180,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
47,5794,10820,Community and social service occupations_Female,2558,6433,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
48,1423,2469,Legal occupations_Female,1263,1361,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
49,5676,19334,"Educational instruction, and library occupatio...",5373,10027,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
50,1435,3475,"Arts, design, entertainment, sports, and media...",2415,1359,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
51,8914,21058,Healthcare practitioners and technical occupat...,3471,10679,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
52,6029,12660,Health diagnosing and treating practitioners a...,2108,6489,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
53,2885,8398,Health technologists and technicians_Female,1363,4190,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
54,47695,71541,Service occupations:_Female,19553,34187,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
55,25274,39251,Healthcare support occupations_Female,7557,18517,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
56,5431,8914,Protective service occupations:_Female,2550,4337,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
57,3905,6054,"Firefighting and prevention, and other protect...",1794,2642,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
58,1526,2860,Law enforcement workers including supervisors_...,756,1695,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
59,6040,5596,Food preparation and serving related occupatio...,1883,2365,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
60,4752,6418,Building and grounds cleaning and maintenance ...,1950,2767,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
61,6198,11362,Personal care and service occupations_Female,5613,6201,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
62,29584,45544,Sales and office occupations:_Female,13593,28843,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
63,9987,15754,Sales and related occupations_Female,5936,9539,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
64,19597,29790,Office and administrative support occupations_...,7657,19304,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
65,375,905,"Natural resources, construction, and maintenan...",652,779,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
66,0,0,"Farming, fishing, and forestry occupations_Female",114,0,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
67,303,662,Construction and extraction occupations_Female,196,306,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
68,72,243,"Installation, maintenance, and repair occupati...",342,473,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
69,5647,9255,"Production, transportation, and material movin...",1367,3851,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
70,2222,2053,Production occupations_Female,303,857,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
71,2200,5023,Transportation occupations_Female,539,1977,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019
72,1225,2179,Material moving occupations_Female,525,1017,NaN,BLACK OR AFRICAN AMERICAN ALONE,2019

In [71]:
HISPANIC_OR_LATINO2010 = pd.read_csv(r"./2010_HISPANIC_OR_LATINO.csv")
HISPANIC_OR_LATINO2011 = pd.read_csv(r"./2011_HISPANIC_OR_LATINO.csv")
HISPANIC_OR_LATINO2012 = pd.read_csv(r"./2012_HISPANIC_OR_LATINO.csv")
HISPANIC_OR_LATINO2013 = pd.read_csv(r"./2013_HISPANIC_OR_LATINO.csv")
HISPANIC_OR_LATINO2014 = pd.read_csv(r"./2014_HISPANIC_OR_LATINO.csv")
HISPANIC_OR_LATINO2015 = pd.read_csv(r"./2015_HISPANIC_OR_LATINO.csv")
HISPANIC_OR_LATINO2016 = pd.read_csv(r"./2016_HISPANIC_OR_LATINO.csv")
HISPANIC_OR_LATINO2017 = pd.read_csv(r"./2017_HISPANIC_OR_LATINO.csv")
HISPANIC_OR_LATINO2018 = pd.read_csv(r"./2018_HISPANIC_OR_LATINO.csv")
HISPANIC_OR_LATINO2019 = pd.read_csv(r"./2019_HISPANIC_OR_LATINO.csv")

In [72]:
HISPANIC_OR_LATINO2010["year"] = HISPANIC_OR_LATINO2010.apply(lambda x: 2010, axis=1)
HISPANIC_OR_LATINO2010["race"] = HISPANIC_OR_LATINO2010.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2010.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2010.loc[37:72, "Label"] += "_Female"
HISPANIC_OR_LATINO2011["year"] = HISPANIC_OR_LATINO2011.apply(lambda x: 2011, axis=1)
HISPANIC_OR_LATINO2011["race"] = HISPANIC_OR_LATINO2011.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2011.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2011.loc[37:72, "Label"] += "_Female"
HISPANIC_OR_LATINO2012["year"] = HISPANIC_OR_LATINO2012.apply(lambda x: 2012, axis=1)
HISPANIC_OR_LATINO2012["race"] = HISPANIC_OR_LATINO2012.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2012.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2012.loc[37:72, "Label"] += "_Female"
HISPANIC_OR_LATINO2013["year"] = HISPANIC_OR_LATINO2013.apply(lambda x: 2013, axis=1)
HISPANIC_OR_LATINO2013["race"] = HISPANIC_OR_LATINO2013.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2013.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2013.loc[37:72, "Label"] += "_Female"
HISPANIC_OR_LATINO2014["year"] = HISPANIC_OR_LATINO2014.apply(lambda x: 2014, axis=1)
HISPANIC_OR_LATINO2014["race"] = HISPANIC_OR_LATINO2014.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2014.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2014.loc[37:72, "Label"] += "_Female"
HISPANIC_OR_LATINO2015["year"] = HISPANIC_OR_LATINO2015.apply(lambda x: 2015, axis=1)
HISPANIC_OR_LATINO2015["race"] = HISPANIC_OR_LATINO2015.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2015.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2015.loc[37:72, "Label"] += "_Female"
HISPANIC_OR_LATINO2016["year"] = HISPANIC_OR_LATINO2016.apply(lambda x: 2016, axis=1)
HISPANIC_OR_LATINO2016["race"] = HISPANIC_OR_LATINO2016.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2016.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2016.loc[37:72, "Label"] += "_Female"
HISPANIC_OR_LATINO2017["year"] = HISPANIC_OR_LATINO2017.apply(lambda x: 2017, axis=1)
HISPANIC_OR_LATINO2017["race"] = HISPANIC_OR_LATINO2017.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2017.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2017.loc[37:72, "Label"] += "_Female"
HISPANIC_OR_LATINO2018["year"] = HISPANIC_OR_LATINO2018.apply(lambda x: 2018, axis=1)
HISPANIC_OR_LATINO2018["race"] = HISPANIC_OR_LATINO2018.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2018.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2018.loc[37:72, "Label"] += "_Female"
HISPANIC_OR_LATINO2019["year"] = HISPANIC_OR_LATINO2019.apply(lambda x: 2019, axis=1)
HISPANIC_OR_LATINO2019["race"] = HISPANIC_OR_LATINO2019.apply(lambda x: "HISPANIC OR LATINO", axis=1)
HISPANIC_OR_LATINO2019.loc[2:36, "Label"] += "_Male"
HISPANIC_OR_LATINO2019.loc[37:72, "Label"] += "_Female"
frames = [HISPANIC_OR_LATINO2010,HISPANIC_OR_LATINO2011,HISPANIC_OR_LATINO2012,
          HISPANIC_OR_LATINO2013,HISPANIC_OR_LATINO2014,HISPANIC_OR_LATINO2015,
          HISPANIC_OR_LATINO2016,HISPANIC_OR_LATINO2017,HISPANIC_OR_LATINO2018,
          HISPANIC_OR_LATINO2019]
HISPANIC_OR_LATINO = pd.concat(frames)
HISPANIC_OR_LATINO = HISPANIC_OR_LATINO.rename(columns={"Bronx County, New York / Estimate":"Bronx County, New York",
                                                                                  "Kings County, New York / Estimate":"Kings County, New York",
                                                                                  "New York County, New York / Estimate":"New York County, New York",
                                                                                  "Queens County, New York / Estimate":"Queens County, New York",
                                                                                  "Richmond County, New York / Estimate":"Richmond County, New York"})
HISPANIC_OR_LATINO

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:45: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,"Bronx County, New York","Kings County, New York",Label,"New York County, New York","Queens County, New York","Richmond County, New York",race,year
0,272862,198296,Total:,165478,298260,31890,HISPANIC OR LATINO,2010
1,140811,109180,Male:,86537,172995,17006,HISPANIC OR LATINO,2010
2,16722,16553,"Management, business, science, and arts occupa...",21667,23523,3476,HISPANIC OR LATINO,2010
3,7407,7107,"Management, business, and financial occupation...",10337,10973,2027,HISPANIC OR LATINO,2010
4,5541,5681,Management occupations_Male,6763,7414,1715,HISPANIC OR LATINO,2010
5,1866,1426,Business and financial operations occupations_...,3574,3559,312,HISPANIC OR LATINO,2010
6,2161,1676,"Computer, engineering, and science occupations...",2603,3950,734,HISPANIC OR LATINO,2010
7,1545,748,Computer and mathematical occupations_Male,1137,2376,522,HISPANIC OR LATINO,2010
8,420,590,Architecture and engineering occupations_Male,991,1454,212,HISPANIC OR LATINO,2010
9,196,338,"Life, physical, and social science occupations...",475,120,0,HISPANIC OR LATINO,2010
10,5914,6612,"Education, legal, community service, arts, and...",6689,6192,468,HISPANIC OR LATINO,2010
11,1619,1307,Community and social service occupations_Male,1249,1006,0,HISPANIC OR LATINO,2010
12,249,532,Legal occupations_Male,567,383,75,HISPANIC OR LATINO,2010
13,2548,1678,"Education, training, and library occupations_Male",2170,2559,68,HISPANIC OR LATINO,2010
14,1498,3095,"Arts, design, entertainment, sports, and media...",2703,2244,325,HISPANIC OR LATINO,2010
15,1240,1158,Healthcare practitioners and technical occupat...,2038,2408,247,HISPANIC OR LATINO,2010
16,464,330,Health diagnosing and treating practitioners a...,1576,1026,166,HISPANIC OR LATINO,2010
17,776,828,Health technologists and technicians_Male,462,1382,81,HISPANIC OR LATINO,2010
18,44552,32002,Service occupations:_Male,26099,49742,4219,HISPANIC OR LATINO,2010
19,982,406,Healthcare support occupations_Male,194,488,487,HISPANIC OR LATINO,2010
20,6553,4705,Protective service occupations:_Male,2884,5776,1165,HISPANIC OR LATINO,2010
21,4786,3415,"Fire fighting and prevention, and other protec...",2178,3019,729,HISPANIC OR LATINO,2010
22,1767,1290,Law enforcement workers including supervisors_...,706,2757,436,HISPANIC OR LATINO,2010
23,14132,13577,Food preparation and serving related occupatio...,11097,24163,994,HISPANIC OR LATINO,2010
24,17356,10683,Building and grounds cleaning and maintenance ...,8295,14744,919,HISPANIC OR LATINO,2010
25,5529,2631,Personal care and service occupations_Male,3629,4571,654,HISPANIC OR LATINO,2010
26,25688,20014,Sales and office occupations:_Male,16924,27284,3201,HISPANIC OR LATINO,2010
27,13067,9829,Sales and related occupations_Male,8052,12569,2085,HISPANIC OR LATINO,2010
28,12621,10185,Office and administrative support occupations_...,8872,14715,1116,HISPANIC OR LATINO,2010
29,22346,19392,"Natural resources, construction, and maintenan...",7235,39597,3636,HISPANIC OR LATINO,2010
...,...,...,...,...,...,...,...,...
43,656,1315,Computer and mathematical occupations_Female,357,710,121,HISPANIC OR LATINO,2019
44,386,334,Architecture and engineering occupations_Female,427,539,239,HISPANIC OR LATINO,2019
45,117,415,"Life, physical, and social science occupations...",1185,87,100,HISPANIC OR LATINO,2019
46,20028,15734,"Education, legal, community service, arts, and...",17099,19062,3034,HISPANIC OR LATINO,2019
47,7098,3926,Community and social service occupations_Female,3300,3381,812,HISPANIC OR LATINO,2019
48,1237,1563,Legal occupations_Female,1801,1294,340,HISPANIC OR LATINO,2019
49,10323,6758,"Educational instruction, and library occupatio...",8670,12424,1547,HISPANIC OR LATINO,2019
50,1370,3487,"Arts, design, entertainment, sports, and media...",3328,1963,335,HISPANIC OR LATINO,2019
51,6191,4180,Healthcare practitioners and technical occupat...,4430,4264,1048,HISPANIC OR LATINO,2019
52,2910,2090,Health diagnosing and treating practitioners a...,1596,2939,760,HISPANIC OR LATINO,2019
53,3281,2090,Health technologists and technicians_Female,2834,1325,288,HISPANIC OR LATINO,2019
54,72364,36964,Service occupations:_Female,31413,56012,5751,HISPANIC OR LATINO,2019
55,35192,14467,Healthcare support occupations_Female,13272,13934,1793,HISPANIC OR LATINO,2019
56,4241,1200,Protective service occupations:_Female,1549,1727,373,HISPANIC OR LATINO,2019
57,3046,662,"Firefighting and prevention, and other protect...",1079,1230,0,HISPANIC OR LATINO,2019
58,1195,538,Law enforcement workers including supervisors_...,470,497,373,HISPANIC OR LATINO,2019
59,11087,4576,Food preparation and serving related occupatio...,5633,12078,570,HISPANIC OR LATINO,2019
60,9111,9764,Building and grounds cleaning and maintenance ...,4565,18103,1673,HISPANIC OR LATINO,2019
61,12733,6957,Personal care and service occupations_Female,6394,10170,1342,HISPANIC OR LATINO,2019
62,42680,27152,Sales and office occupations:_Female,23525,38517,4150,HISPANIC OR LATINO,2019
63,15420,10083,Sales and related occupations_Female,10148,15238,2512,HISPANIC OR LATINO,2019
64,27260,17069,Office and administrative support occupations_...,13377,23279,1638,HISPANIC OR LATINO,2019
65,1027,1038,"Natural resources, construction, and maintenan...",1207,2052,268,HISPANIC OR LATINO,2019
66,518,79,"Farming, fishing, and forestry occupations_Female",295,272,268,HISPANIC OR LATINO,2019
67,176,782,Construction and extraction occupations_Female,645,1361,0,HISPANIC OR LATINO,2019
68,333,177,"Installation, maintenance, and repair occupati...",267,419,0,HISPANIC OR LATINO,2019
69,10344,5642,"Production, transportation, and material movin...",3954,9805,363,HISPANIC OR LATINO,2019
70,4814,2292,Production occupations_Female,1430,5527,181,HISPANIC OR LATINO,2019
71,2840,1496,Transportation occupations_Female,754,2075,182,HISPANIC OR LATINO,2019
72,2690,1854,Material moving occupations_Female,1770,2203,0,HISPANIC OR LATINO,2019

In [73]:
SomeOtherRaceAlone2010 = pd.read_csv(r"./2010_SomeOtherRaceAlone.csv")
SomeOtherRaceAlone2011 = pd.read_csv(r"./2011_SomeOtherRaceAlone.csv")
SomeOtherRaceAlone2012 = pd.read_csv(r"./2012_SomeOtherRaceAlone.csv")
SomeOtherRaceAlone2013 = pd.read_csv(r"./2013_SomeOtherRaceAlone.csv")
SomeOtherRaceAlone2014 = pd.read_csv(r"./2014_SomeOtherRaceAlone.csv")
SomeOtherRaceAlone2015 = pd.read_csv(r"./2015_SomeOtherRaceAlone.csv")
SomeOtherRaceAlone2016 = pd.read_csv(r"./2016_SomeOtherRaceAlone.csv")
SomeOtherRaceAlone2017 = pd.read_csv(r"./2017_SomeOtherRaceAlone.csv")
SomeOtherRaceAlone2018 = pd.read_csv(r"./2018_SomeOtherRaceAlone.csv")
SomeOtherRaceAlone2019 = pd.read_csv(r"./2019_SomeOtherRaceAlone.csv")

In [74]:
SomeOtherRaceAlone2010["year"] = SomeOtherRaceAlone2010.apply(lambda x: 2010, axis=1)
SomeOtherRaceAlone2010["race"] = SomeOtherRaceAlone2010.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2010.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2010.loc[37:72, "Label"] += "_Female"
SomeOtherRaceAlone2011["year"] = SomeOtherRaceAlone2011.apply(lambda x: 2011, axis=1)
SomeOtherRaceAlone2011["race"] = SomeOtherRaceAlone2011.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2011.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2011.loc[37:72, "Label"] += "_Female"
SomeOtherRaceAlone2012["year"] = SomeOtherRaceAlone2012.apply(lambda x: 2012, axis=1)
SomeOtherRaceAlone2012["race"] = SomeOtherRaceAlone2012.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2012.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2012.loc[37:72, "Label"] += "_Female"
SomeOtherRaceAlone2013["year"] = SomeOtherRaceAlone2013.apply(lambda x: 2013, axis=1)
SomeOtherRaceAlone2013["race"] = SomeOtherRaceAlone2013.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2013.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2013.loc[37:72, "Label"] += "_Female"
SomeOtherRaceAlone2014["year"] = SomeOtherRaceAlone2014.apply(lambda x: 2014, axis=1)
SomeOtherRaceAlone2014["race"] = SomeOtherRaceAlone2014.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2014.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2014.loc[37:72, "Label"] += "_Female"
SomeOtherRaceAlone2015["year"] = SomeOtherRaceAlone2015.apply(lambda x: 2015, axis=1)
SomeOtherRaceAlone2015["race"] = SomeOtherRaceAlone2015.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2015.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2015.loc[37:72, "Label"] += "_Female"
SomeOtherRaceAlone2016["year"] = SomeOtherRaceAlone2016.apply(lambda x: 2016, axis=1)
SomeOtherRaceAlone2016["race"] = SomeOtherRaceAlone2016.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2016.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2016.loc[37:72, "Label"] += "_Female"
SomeOtherRaceAlone2017["year"] = SomeOtherRaceAlone2017.apply(lambda x: 2017, axis=1)
SomeOtherRaceAlone2017["race"] = SomeOtherRaceAlone2017.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2017.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2017.loc[37:72, "Label"] += "_Female"
SomeOtherRaceAlone2018["year"] = SomeOtherRaceAlone2018.apply(lambda x: 2018, axis=1)
SomeOtherRaceAlone2018["race"] = SomeOtherRaceAlone2018.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2018.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2018.loc[37:72, "Label"] += "_Female"
SomeOtherRaceAlone2019["year"] = SomeOtherRaceAlone2019.apply(lambda x: 2019, axis=1)
SomeOtherRaceAlone2019["race"] = SomeOtherRaceAlone2019.apply(lambda x: "Some Other Race Alone", axis=1)
SomeOtherRaceAlone2019.loc[2:36, "Label"] += "_Male"
SomeOtherRaceAlone2019.loc[37:72, "Label"] += "_Female"
frames = [SomeOtherRaceAlone2010,SomeOtherRaceAlone2011,SomeOtherRaceAlone2012,
          SomeOtherRaceAlone2013,SomeOtherRaceAlone2014,SomeOtherRaceAlone2015,
          SomeOtherRaceAlone2016,SomeOtherRaceAlone2017,SomeOtherRaceAlone2018,
          SomeOtherRaceAlone2019]
SomeOtherRaceAlone = pd.concat(frames)
SomeOtherRaceAlone = SomeOtherRaceAlone.rename(columns={"Bronx County, New York / Estimate":"Bronx County, New York",
                                                                                  "Kings County, New York / Estimate":"Kings County, New York",
                                                                                  "New York County, New York / Estimate":"New York County, New York",
                                                                                  "Queens County, New York / Estimate":"Queens County, New York",
                                                                                  "Richmond County, New York / Estimate":"Richmond County, New York"})
SomeOtherRaceAlone

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:45: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,"Bronx County, New York","Kings County, New York",Label,"New York County, New York","Queens County, New York","Richmond County, New York",race,year
0,179576,84438,Total:,75334,136409,NaN,Some Other Race Alone,2010
1,96201,48456,Male:,42397,77334,NaN,Some Other Race Alone,2010
2,10280,7535,"Management, business, science, and arts occupa...",7667,9230,NaN,Some Other Race Alone,2010
3,4551,3150,"Management, business, and financial occupation...",3707,4517,NaN,Some Other Race Alone,2010
4,3447,2827,Management occupations_Male,2725,3381,NaN,Some Other Race Alone,2010
5,1104,323,Business and financial operations occupations_...,982,1136,NaN,Some Other Race Alone,2010
6,1576,537,"Computer, engineering, and science occupations...",769,1171,NaN,Some Other Race Alone,2010
7,1162,226,Computer and mathematical occupations_Male,179,521,NaN,Some Other Race Alone,2010
8,316,163,Architecture and engineering occupations_Male,513,508,NaN,Some Other Race Alone,2010
9,98,148,"Life, physical, and social science occupations...",77,142,NaN,Some Other Race Alone,2010
10,3697,3336,"Education, legal, community service, arts, and...",2540,2392,NaN,Some Other Race Alone,2010
11,734,442,Community and social service occupations_Male,507,532,NaN,Some Other Race Alone,2010
12,0,384,Legal occupations_Male,235,0,NaN,Some Other Race Alone,2010
13,1882,783,"Education, training, and library occupations_Male",481,1023,NaN,Some Other Race Alone,2010
14,1081,1727,"Arts, design, entertainment, sports, and media...",1317,837,NaN,Some Other Race Alone,2010
15,456,512,Healthcare practitioners and technical occupat...,651,1150,NaN,Some Other Race Alone,2010
16,116,52,Health diagnosing and treating practitioners a...,341,576,NaN,Some Other Race Alone,2010
17,340,460,Health technologists and technicians_Male,310,574,NaN,Some Other Race Alone,2010
18,30676,13411,Service occupations:_Male,14859,22317,NaN,Some Other Race Alone,2010
19,796,63,Healthcare support occupations_Male,99,127,NaN,Some Other Race Alone,2010
20,3648,1961,Protective service occupations:_Male,1015,2980,NaN,Some Other Race Alone,2010
21,2330,1552,"Fire fighting and prevention, and other protec...",611,1529,NaN,Some Other Race Alone,2010
22,1318,409,Law enforcement workers including supervisors_...,404,1451,NaN,Some Other Race Alone,2010
23,10435,6471,Food preparation and serving related occupatio...,6600,10478,NaN,Some Other Race Alone,2010
24,12179,4177,Building and grounds cleaning and maintenance ...,5280,6888,NaN,Some Other Race Alone,2010
25,3618,739,Personal care and service occupations_Male,1865,1844,NaN,Some Other Race Alone,2010
26,16251,8285,Sales and office occupations:_Male,7362,12897,NaN,Some Other Race Alone,2010
27,8491,3835,Sales and related occupations_Male,3891,5937,NaN,Some Other Race Alone,2010
28,7760,4450,Office and administrative support occupations_...,3471,6960,NaN,Some Other Race Alone,2010
29,16685,9948,"Natural resources, construction, and maintenan...",3614,18413,NaN,Some Other Race Alone,2010
...,...,...,...,...,...,...,...,...
43,222,289,Computer and mathematical occupations_Female,84,224,NaN,Some Other Race Alone,2019
44,0,0,Architecture and engineering occupations_Female,142,194,NaN,Some Other Race Alone,2019
45,0,132,"Life, physical, and social science occupations...",168,0,NaN,Some Other Race Alone,2019
46,10189,5664,"Education, legal, community service, arts, and...",6586,7340,NaN,Some Other Race Alone,2019
47,3553,1001,Community and social service occupations_Female,1912,628,NaN,Some Other Race Alone,2019
48,664,392,Legal occupations_Female,169,494,NaN,Some Other Race Alone,2019
49,5436,3207,"Educational instruction, and library occupatio...",4009,5527,NaN,Some Other Race Alone,2019
50,536,1064,"Arts, design, entertainment, sports, and media...",496,691,NaN,Some Other Race Alone,2019
51,2258,1551,Healthcare practitioners and technical occupat...,1782,2219,NaN,Some Other Race Alone,2019
52,1046,677,Health diagnosing and treating practitioners a...,487,1012,NaN,Some Other Race Alone,2019
53,1212,874,Health technologists and technicians_Female,1295,1207,NaN,Some Other Race Alone,2019
54,43891,21279,Service occupations:_Female,15635,32893,NaN,Some Other Race Alone,2019
55,21312,7326,Healthcare support occupations_Female,7406,8666,NaN,Some Other Race Alone,2019
56,1688,534,Protective service occupations:_Female,688,966,NaN,Some Other Race Alone,2019
57,1118,432,"Firefighting and prevention, and other protect...",390,686,NaN,Some Other Race Alone,2019
58,570,102,Law enforcement workers including supervisors_...,298,280,NaN,Some Other Race Alone,2019
59,6356,2612,Food preparation and serving related occupatio...,2859,7216,NaN,Some Other Race Alone,2019
60,6306,6657,Building and grounds cleaning and maintenance ...,2247,11052,NaN,Some Other Race Alone,2019
61,8229,4150,Personal care and service occupations_Female,2435,4993,NaN,Some Other Race Alone,2019
62,21539,11598,Sales and office occupations:_Female,10521,18372,NaN,Some Other Race Alone,2019
63,7891,4473,Sales and related occupations_Female,4990,8319,NaN,Some Other Race Alone,2019
64,13648,7125,Office and administrative support occupations_...,5531,10053,NaN,Some Other Race Alone,2019
65,587,360,"Natural resources, construction, and maintenan...",604,1357,NaN,Some Other Race Alone,2019
66,379,0,"Farming, fishing, and forestry occupations_Female",181,226,NaN,Some Other Race Alone,2019
67,97,183,Construction and extraction occupations_Female,200,954,NaN,Some Other Race Alone,2019
68,111,177,"Installation, maintenance, and repair occupati...",223,177,NaN,Some Other Race Alone,2019
69,5833,2368,"Production, transportation, and material movin...",2599,4450,NaN,Some Other Race Alone,2019
70,2759,682,Production occupations_Female,1284,2857,NaN,Some Other Race Alone,2019
71,1443,679,Transportation occupations_Female,0,542,NaN,Some Other Race Alone,2019
72,1631,1007,Material moving occupations_Female,1315,1051,NaN,Some Other Race Alone,2019

In [75]:
Two_or_More_Races2010 = pd.read_csv(r"./2010_Two_or_More_Races.csv")
Two_or_More_Races2011 = pd.read_csv(r"./2011_Two_or_More_Races.csv")
Two_or_More_Races2012 = pd.read_csv(r"./2012_Two_or_More_Races.csv")
Two_or_More_Races2013 = pd.read_csv(r"./2013_Two_or_More_Races.csv")
Two_or_More_Races2014 = pd.read_csv(r"./2014_Two_or_More_Races.csv")
Two_or_More_Races2015 = pd.read_csv(r"./2015_Two_or_More_Races.csv")
Two_or_More_Races2016 = pd.read_csv(r"./2016_Two_or_More_Races.csv")
Two_or_More_Races2017 = pd.read_csv(r"./2017_Two_or_More_Races.csv")
Two_or_More_Races2018 = pd.read_csv(r"./2018_Two_or_More_Races.csv")
Two_or_More_Races2019 = pd.read_csv(r"./2019_Two_or_More_Races.csv")

In [76]:
Two_or_More_Races2010["year"] = Two_or_More_Races2010.apply(lambda x: 2010, axis=1)
Two_or_More_Races2010["race"] = Two_or_More_Races2010.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2010.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2010.loc[37:72, "Label"] += "_Female"
Two_or_More_Races2011["year"] = Two_or_More_Races2011.apply(lambda x: 2011, axis=1)
Two_or_More_Races2011["race"] = Two_or_More_Races2011.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2011.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2011.loc[37:72, "Label"] += "_Female"
Two_or_More_Races2012["year"] = Two_or_More_Races2012.apply(lambda x: 2012, axis=1)
Two_or_More_Races2012["race"] = Two_or_More_Races2012.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2012.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2012.loc[37:72, "Label"] += "_Female"
Two_or_More_Races2013["year"] = Two_or_More_Races2013.apply(lambda x: 2013, axis=1)
Two_or_More_Races2013["race"] = Two_or_More_Races2013.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2013.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2013.loc[37:72, "Label"] += "_Female"
Two_or_More_Races2014["year"] = Two_or_More_Races2014.apply(lambda x: 2014, axis=1)
Two_or_More_Races2014["race"] = Two_or_More_Races2014.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2014.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2014.loc[37:72, "Label"] += "_Female"
Two_or_More_Races2015["year"] = Two_or_More_Races2015.apply(lambda x: 2015, axis=1)
Two_or_More_Races2015["race"] = Two_or_More_Races2015.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2015.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2015.loc[37:72, "Label"] += "_Female"
Two_or_More_Races2016["year"] = Two_or_More_Races2016.apply(lambda x: 2016, axis=1)
Two_or_More_Races2016["race"] = Two_or_More_Races2016.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2016.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2016.loc[37:72, "Label"] += "_Female"
Two_or_More_Races2017["year"] = Two_or_More_Races2017.apply(lambda x: 2017, axis=1)
Two_or_More_Races2017["race"] = Two_or_More_Races2017.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2017.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2017.loc[37:72, "Label"] += "_Female"
Two_or_More_Races2018["year"] = Two_or_More_Races2018.apply(lambda x: 2018, axis=1)
Two_or_More_Races2018["race"] = Two_or_More_Races2018.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2018.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2018.loc[37:72, "Label"] += "_Female"
Two_or_More_Races2019["year"] = Two_or_More_Races2019.apply(lambda x: 2019, axis=1)
Two_or_More_Races2019["race"] = Two_or_More_Races2019.apply(lambda x: "Two or More Races", axis=1)
Two_or_More_Races2019.loc[2:36, "Label"] += "_Male"
Two_or_More_Races2019.loc[37:72, "Label"] += "_Female"
frames = [Two_or_More_Races2010,Two_or_More_Races2011,Two_or_More_Races2012,
          Two_or_More_Races2013,Two_or_More_Races2014,Two_or_More_Races2015,
          Two_or_More_Races2016,Two_or_More_Races2017,Two_or_More_Races2018,
          Two_or_More_Races2019]
Two_or_More_Races = pd.concat(frames)
Two_or_More_Races = Two_or_More_Races.rename(columns={"Bronx County, New York / Estimate":"Bronx County, New York",
                                                                                  "Kings County, New York / Estimate":"Kings County, New York",
                                                                                  "New York County, New York / Estimate":"New York County, New York",
                                                                                  "Queens County, New York / Estimate":"Queens County, New York",
                                                                                  "Richmond County, New York / Estimate":"Richmond County, New York"})
Two_or_More_Races

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:45: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,"Bronx County, New York","Kings County, New York",Label,"New York County, New York","Queens County, New York",race,year
0,NaN,15798,Total:,27255.0,30488,Two or More Races,2010
1,NaN,8756,Male:,11771.0,16093,Two or More Races,2010
2,NaN,3303,"Management, business, science, and arts occupa...",5298.0,4512,Two or More Races,2010
3,NaN,1515,"Management, business, and financial occupation...",2348.0,2505,Two or More Races,2010
4,NaN,1126,Management occupations_Male,1589.0,1569,Two or More Races,2010
5,NaN,389,Business and financial operations occupations_...,759.0,936,Two or More Races,2010
6,NaN,274,"Computer, engineering, and science occupations...",432.0,1418,Two or More Races,2010
7,NaN,190,Computer and mathematical occupations_Male,282.0,806,Two or More Races,2010
8,NaN,84,Architecture and engineering occupations_Male,71.0,281,Two or More Races,2010
9,NaN,0,"Life, physical, and social science occupations...",79.0,331,Two or More Races,2010
10,NaN,1437,"Education, legal, community service, arts, and...",2084.0,368,Two or More Races,2010
11,NaN,0,Community and social service occupations_Male,0.0,57,Two or More Races,2010
12,NaN,41,Legal occupations_Male,568.0,0,Two or More Races,2010
13,NaN,243,"Education, training, and library occupations_Male",443.0,210,Two or More Races,2010
14,NaN,1153,"Arts, design, entertainment, sports, and media...",1073.0,101,Two or More Races,2010
15,NaN,77,Healthcare practitioners and technical occupat...,434.0,221,Two or More Races,2010
16,NaN,77,Health diagnosing and treating practitioners a...,282.0,108,Two or More Races,2010
17,NaN,0,Health technologists and technicians_Male,152.0,113,Two or More Races,2010
18,NaN,1711,Service occupations:_Male,2574.0,3756,Two or More Races,2010
19,NaN,55,Healthcare support occupations_Male,0.0,48,Two or More Races,2010
20,NaN,516,Protective service occupations:_Male,329.0,513,Two or More Races,2010
21,NaN,364,"Fire fighting and prevention, and other protec...",287.0,265,Two or More Races,2010
22,NaN,152,Law enforcement workers including supervisors_...,42.0,248,Two or More Races,2010
23,NaN,340,Food preparation and serving related occupatio...,994.0,2229,Two or More Races,2010
24,NaN,618,Building and grounds cleaning and maintenance ...,857.0,754,Two or More Races,2010
25,NaN,182,Personal care and service occupations_Male,394.0,212,Two or More Races,2010
26,NaN,1915,Sales and office occupations:_Male,2010.0,3672,Two or More Races,2010
27,NaN,1055,Sales and related occupations_Male,851.0,2036,Two or More Races,2010
28,NaN,860,Office and administrative support occupations_...,1159.0,1636,Two or More Races,2010
29,NaN,554,"Natural resources, construction, and maintenan...",948.0,1665,Two or More Races,2010
...,...,...,...,...,...,...,...
43,59.0,327,Computer and mathematical occupations_Female,650.0,300,Two or More Races,2019
44,74.0,42,Architecture and engineering occupations_Female,401.0,26,Two or More Races,2019
45,0.0,357,"Life, physical, and social science occupations...",165.0,64,Two or More Races,2019
46,1905.0,4597,"Education, legal, community service, arts, and...",4250.0,2652,Two or More Races,2019
47,813.0,341,Community and social service occupations_Female,184.0,338,Two or More Races,2019
48,127.0,558,Legal occupations_Female,668.0,133,Two or More Races,2019
49,910.0,1872,"Educational instruction, and library occupatio...",2127.0,1572,Two or More Races,2019
50,55.0,1826,"Arts, design, entertainment, sports, and media...",1271.0,609,Two or More Races,2019
51,744.0,1106,Healthcare practitioners and technical occupat...,767.0,1335,Two or More Races,2019
52,340.0,419,Health diagnosing and treating practitioners a...,737.0,852,Two or More Races,2019
53,404.0,687,Health technologists and technicians_Female,30.0,483,Two or More Races,2019
54,4654.0,4377,Service occupations:_Female,4962.0,4847,Two or More Races,2019
55,2210.0,2305,Healthcare support occupations_Female,2092.0,1700,Two or More Races,2019
56,127.0,96,Protective service occupations:_Female,247.0,249,Two or More Races,2019
57,127.0,96,"Firefighting and prevention, and other protect...",247.0,249,Two or More Races,2019
58,0.0,0,Law enforcement workers including supervisors_...,0.0,0,Two or More Races,2019
59,661.0,644,Food preparation and serving related occupatio...,901.0,1274,Two or More Races,2019
60,606.0,551,Building and grounds cleaning and maintenance ...,451.0,1162,Two or More Races,2019
61,1050.0,781,Personal care and service occupations_Female,1271.0,462,Two or More Races,2019
62,3067.0,4418,Sales and office occupations:_Female,3395.0,6466,Two or More Races,2019
63,1325.0,1184,Sales and related occupations_Female,868.0,2932,Two or More Races,2019
64,1742.0,3234,Office and administrative support occupations_...,2527.0,3534,Two or More Races,2019
65,82.0,110,"Natural resources, construction, and maintenan...",0.0,77,Two or More Races,2019
66,0.0,79,"Farming, fishing, and forestry occupations_Female",0.0,0,Two or More Races,2019
67,0.0,31,Construction and extraction occupations_Female,0.0,0,Two or More Races,2019
68,82.0,0,"Installation, maintenance, and repair occupati...",0.0,77,Two or More Races,2019
69,797.0,337,"Production, transportation, and material movin...",350.0,791,Two or More Races,2019
70,316.0,337,Production occupations_Female,28.0,114,Two or More Races,2019
71,481.0,0,Transportation occupations_Female,155.0,445,Two or More Races,2019
72,0.0,0,Material moving occupations_Female,167.0,232,Two or More Races,2019

In [77]:
White_Alone2010 = pd.read_csv(r"./2010_White_Alone.csv")
White_Alone2011 = pd.read_csv(r"./2011_White_Alone.csv")
White_Alone2012 = pd.read_csv(r"./2012_White_Alone.csv")
White_Alone2013 = pd.read_csv(r"./2013_White_Alone.csv")
White_Alone2014 = pd.read_csv(r"./2014_White_Alone.csv")
White_Alone2015 = pd.read_csv(r"./2015_White_Alone.csv")
White_Alone2016 = pd.read_csv(r"./2016_White_Alone.csv")
White_Alone2017 = pd.read_csv(r"./2017_White_Alone.csv")
White_Alone2018 = pd.read_csv(r"./2018_White_Alone.csv")
White_Alone2019 = pd.read_csv(r"./2019_White_Alone.csv")

In [78]:
White_Alone2010["year"] = White_Alone2010.apply(lambda x: 2010, axis=1)
White_Alone2010["race"] = White_Alone2010.apply(lambda x: "White Alone", axis=1)
White_Alone2010.loc[2:36, "Label"] += "_Male"
White_Alone2010.loc[37:72, "Label"] += "_Female"
White_Alone2011["year"] = White_Alone2011.apply(lambda x: 2011, axis=1)
White_Alone2011["race"] = White_Alone2011.apply(lambda x: "White Alone", axis=1)
White_Alone2011.loc[2:36, "Label"] += "_Male"
White_Alone2011.loc[37:72, "Label"] += "_Female"
White_Alone2012["year"] = White_Alone2012.apply(lambda x: 2012, axis=1)
White_Alone2012["race"] = White_Alone2012.apply(lambda x: "White Alone", axis=1)
White_Alone2012.loc[2:36, "Label"] += "_Male"
White_Alone2012.loc[37:72, "Label"] += "_Female"
White_Alone2013["year"] = White_Alone2013.apply(lambda x: 2013, axis=1)
White_Alone2013["race"] = White_Alone2013.apply(lambda x: "White Alone", axis=1)
White_Alone2013.loc[2:36, "Label"] += "_Male"
White_Alone2013.loc[37:72, "Label"] += "_Female"
White_Alone2014["year"] = White_Alone2014.apply(lambda x: 2014, axis=1)
White_Alone2014["race"] = White_Alone2014.apply(lambda x: "White Alone", axis=1)
White_Alone2014.loc[2:36, "Label"] += "_Male"
White_Alone2014.loc[37:72, "Label"] += "_Female"
White_Alone2015["year"] = White_Alone2015.apply(lambda x: 2015, axis=1)
White_Alone2015["race"] = White_Alone2015.apply(lambda x: "White Alone", axis=1)
White_Alone2015.loc[2:36, "Label"] += "_Male"
White_Alone2015.loc[37:72, "Label"] += "_Female"
White_Alone2016["year"] = White_Alone2016.apply(lambda x: 2016, axis=1)
White_Alone2016["race"] = White_Alone2016.apply(lambda x: "White Alone", axis=1)
White_Alone2016.loc[2:36, "Label"] += "_Male"
White_Alone2016.loc[37:72, "Label"] += "_Female"
White_Alone2017["year"] = White_Alone2017.apply(lambda x: 2017, axis=1)
White_Alone2017["race"] = White_Alone2017.apply(lambda x: "White Alone", axis=1)
White_Alone2017.loc[2:36, "Label"] += "_Male"
White_Alone2017.loc[37:72, "Label"] += "_Female"
White_Alone2018["year"] = White_Alone2018.apply(lambda x: 2018, axis=1)
White_Alone2018["race"] = White_Alone2018.apply(lambda x: "White Alone", axis=1)
White_Alone2018.loc[2:36, "Label"] += "_Male"
White_Alone2018.loc[37:72, "Label"] += "_Female"
White_Alone2019["year"] = White_Alone2019.apply(lambda x: 2019, axis=1)
White_Alone2019["race"] = White_Alone2019.apply(lambda x: "White Alone", axis=1)
White_Alone2019.loc[2:36, "Label"] += "_Male"
White_Alone2019.loc[37:72, "Label"] += "_Female"
frames = [White_Alone2010,White_Alone2011,White_Alone2012,
          White_Alone2013,White_Alone2014,White_Alone2015,
          White_Alone2016,White_Alone2017,White_Alone2018,
          White_Alone2019]
White_Alone = pd.concat(frames)
White_Alone = White_Alone.rename(columns={"Bronx County, New York / Estimate":"Bronx County, New York",
                                                                                  "Kings County, New York / Estimate":"Kings County, New York",
                                                                                  "New York County, New York / Estimate":"New York County, New York",
                                                                                  "Queens County, New York / Estimate":"Queens County, New York",
                                                                                  "Richmond County, New York / Estimate":"Richmond County, New York"})
White_Alone

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:45: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,"Bronx County, New York","Kings County, New York",Label,"New York County, New York","Queens County, New York","Richmond County, New York",race,year
0,120733,496204,Total:,542543,444037,153816,White Alone,2010
1,63416,263418,Male:,275189,247364,82619,White Alone,2010
2,15915,114625,"Management, business, science, and arts occupa...",191941,73653,27656,White Alone,2010
3,5949,41094,"Management, business, and financial occupation...",87004,34708,13924,White Alone,2010
4,3971,29009,Management occupations_Male,50751,23656,9817,White Alone,2010
5,1978,12085,Business and financial operations occupations_...,36253,11052,4107,White Alone,2010
6,1834,20622,"Computer, engineering, and science occupations...",22659,10418,5497,White Alone,2010
7,797,13253,Computer and mathematical occupations_Male,13812,6363,3253,White Alone,2010
8,484,5279,Architecture and engineering occupations_Male,4706,3220,1921,White Alone,2010
9,553,2090,"Life, physical, and social science occupations...",4141,835,323,White Alone,2010
10,6383,46683,"Education, legal, community service, arts, and...",71491,22940,5006,White Alone,2010
11,806,4790,Community and social service occupations_Male,3241,2281,487,White Alone,2010
12,1059,7538,Legal occupations_Male,19336,2948,1144,White Alone,2010
13,2576,15174,"Education, training, and library occupations_Male",19820,9245,1999,White Alone,2010
14,1942,19181,"Arts, design, entertainment, sports, and media...",29094,8466,1376,White Alone,2010
15,1749,6226,Healthcare practitioners and technical occupat...,10787,5587,3229,White Alone,2010
16,980,4519,Health diagnosing and treating practitioners a...,10297,3426,2551,White Alone,2010
17,769,1707,Health technologists and technicians_Male,490,2161,678,White Alone,2010
18,15928,36894,Service occupations:_Male,22113,50078,13902,White Alone,2010
19,292,1714,Healthcare support occupations_Male,474,1123,476,White Alone,2010
20,3312,7271,Protective service occupations:_Male,3376,10159,6985,White Alone,2010
21,2667,4076,"Fire fighting and prevention, and other protec...",2273,6145,3890,White Alone,2010
22,645,3195,Law enforcement workers including supervisors_...,1103,4014,3095,White Alone,2010
23,3980,13622,Food preparation and serving related occupatio...,9044,18949,2360,White Alone,2010
24,6061,10076,Building and grounds cleaning and maintenance ...,3593,13121,2594,White Alone,2010
25,2283,4211,Personal care and service occupations_Male,5626,6726,1487,White Alone,2010
26,12940,51629,Sales and office occupations:_Male,48359,44472,13588,White Alone,2010
27,6165,29163,Sales and related occupations_Male,34633,24656,7134,White Alone,2010
28,6775,22466,Office and administrative support occupations_...,13726,19816,6454,White Alone,2010
29,8508,29395,"Natural resources, construction, and maintenan...",5427,43910,14511,White Alone,2010
...,...,...,...,...,...,...,...,...
43,380,5797,Computer and mathematical occupations_Female,8220,2406,1392,White Alone,2019
44,543,2590,Architecture and engineering occupations_Female,2571,808,566,White Alone,2019
45,406,3885,"Life, physical, and social science occupations...",6486,988,462,White Alone,2019
46,9984,77990,"Education, legal, community service, arts, and...",77477,41677,19418,White Alone,2019
47,1534,8577,Community and social service occupations_Female,5344,3877,2197,White Alone,2019
48,342,9188,Legal occupations_Female,13064,4708,2179,White Alone,2019
49,6370,33189,"Educational instruction, and library occupatio...",26804,25794,13099,White Alone,2019
50,1738,27036,"Arts, design, entertainment, sports, and media...",32265,7298,1943,White Alone,2019
51,4335,17650,Healthcare practitioners and technical occupat...,18836,14067,8137,White Alone,2019
52,2705,14368,Health diagnosing and treating practitioners a...,16856,11378,6274,White Alone,2019
53,1630,3282,Health technologists and technicians_Female,1980,2689,1863,White Alone,2019
54,16195,42405,Service occupations:_Female,25178,42870,13295,White Alone,2019
55,6872,16542,Healthcare support occupations_Female,4030,11261,3959,White Alone,2019
56,1435,1709,Protective service occupations:_Female,2365,1906,2144,White Alone,2019
57,1007,914,"Firefighting and prevention, and other protect...",2193,1105,903,White Alone,2019
58,428,795,Law enforcement workers including supervisors_...,172,801,1241,White Alone,2019
59,3095,8890,Food preparation and serving related occupatio...,5648,10027,3055,White Alone,2019
60,2354,3847,Building and grounds cleaning and maintenance ...,2818,9397,1929,White Alone,2019
61,2439,11417,Personal care and service occupations_Female,10317,10279,2208,White Alone,2019
62,17272,57395,Sales and office occupations:_Female,51480,46465,20630,White Alone,2019
63,5221,18838,Sales and related occupations_Female,27995,14984,7136,White Alone,2019
64,12051,38557,Office and administrative support occupations_...,23485,31481,13494,White Alone,2019
65,332,821,"Natural resources, construction, and maintenan...",763,1005,895,White Alone,2019
66,185,0,"Farming, fishing, and forestry occupations_Female",0,107,268,White Alone,2019
67,79,700,Construction and extraction occupations_Female,746,606,142,White Alone,2019
68,68,121,"Installation, maintenance, and repair occupati...",17,292,485,White Alone,2019
69,1837,5730,"Production, transportation, and material movin...",3350,7697,1441,White Alone,2019
70,471,3224,Production occupations_Female,1193,3925,314,White Alone,2019
71,770,993,Transportation occupations_Female,914,2311,476,White Alone,2019
72,596,1513,Material moving occupations_Female,1243,1461,651,White Alone,2019

In [79]:
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2010 = pd.read_csv(r"./2010_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2011 = pd.read_csv(r"./2011_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2012 = pd.read_csv(r"./2012_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2013 = pd.read_csv(r"./2013_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2014 = pd.read_csv(r"./2014_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2015 = pd.read_csv(r"./2015_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2016 = pd.read_csv(r"./2016_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2017 = pd.read_csv(r"./2017_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2018 = pd.read_csv(r"./2018_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2019 = pd.read_csv(r"./2019_WHITE_ALONE_NOT_HISPANIC_OR_LATINO.csv")

In [80]:
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2010["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2010.apply(lambda x: 2010, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2010["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2010.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2010.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2010.loc[37:72, "Label"] += "_Female"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2011["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2011.apply(lambda x: 2011, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2011["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2011.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2011.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2011.loc[37:72, "Label"] += "_Female"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2012["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2012.apply(lambda x: 2012, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2012["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2012.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2012.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2012.loc[37:72, "Label"] += "_Female"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2013["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2013.apply(lambda x: 2013, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2013["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2013.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2013.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2013.loc[37:72, "Label"] += "_Female"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2014["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2014.apply(lambda x: 2014, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2014["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2014.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2014.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2014.loc[37:72, "Label"] += "_Female"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2015["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2015.apply(lambda x: 2015, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2015["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2015.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2015.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2015.loc[37:72, "Label"] += "_Female"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2016["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2016.apply(lambda x: 2016, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2016["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2016.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2016.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2016.loc[37:72, "Label"] += "_Female"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2017["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2017.apply(lambda x: 2017, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2017["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2017.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2017.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2017.loc[37:72, "Label"] += "_Female"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2018["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2018.apply(lambda x: 2018, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2018["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2018.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2018.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2018.loc[37:72, "Label"] += "_Female"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2019["year"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2019.apply(lambda x: 2019, axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2019["race"] = WHITE_ALONE_NOT_HISPANIC_OR_LATINO2019.apply(lambda x: "WHITE ALONE NOT HISPANIC OR LATINO", axis=1)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2019.loc[2:36, "Label"] += "_Male"
WHITE_ALONE_NOT_HISPANIC_OR_LATINO2019.loc[37:72, "Label"] += "_Female"
frames = [WHITE_ALONE_NOT_HISPANIC_OR_LATINO2010,WHITE_ALONE_NOT_HISPANIC_OR_LATINO2011,WHITE_ALONE_NOT_HISPANIC_OR_LATINO2012,
          WHITE_ALONE_NOT_HISPANIC_OR_LATINO2013,WHITE_ALONE_NOT_HISPANIC_OR_LATINO2014,WHITE_ALONE_NOT_HISPANIC_OR_LATINO2015,
          WHITE_ALONE_NOT_HISPANIC_OR_LATINO2016,WHITE_ALONE_NOT_HISPANIC_OR_LATINO2017,WHITE_ALONE_NOT_HISPANIC_OR_LATINO2018,
          WHITE_ALONE_NOT_HISPANIC_OR_LATINO2019]
WHITE_ALONE_NOT_HISPANIC_OR_LATINO = pd.concat(frames)
WHITE_ALONE_NOT_HISPANIC_OR_LATINO = WHITE_ALONE_NOT_HISPANIC_OR_LATINO.rename(columns={"Bronx County, New York / Estimate":"Bronx County, New York",
                                                                                  "Kings County, New York / Estimate":"Kings County, New York",
                                                                                  "New York County, New York / Estimate":"New York County, New York",
                                                                                  "Queens County, New York / Estimate":"Queens County, New York",
                                                                                  "Richmond County, New York / Estimate":"Richmond County, New York"})
WHITE_ALONE_NOT_HISPANIC_OR_LATINO

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:45: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,"Bronx County, New York","Kings County, New York",Label,"New York County, New York","Queens County, New York","Richmond County, New York",race,year
0,62493,407497,Total:,479706,283989,132299,WHITE ALONE NOT HISPANIC OR LATINO,2010
1,32359,215595,Male:,243425,153004,71620,WHITE ALONE NOT HISPANIC OR LATINO,2010
2,11749,107844,"Management, business, science, and arts occupa...",180548,60264,25026,WHITE ALONE NOT HISPANIC OR LATINO,2010
3,4324,38045,"Management, business, and financial occupation...",81321,28543,12479,WHITE ALONE NOT HISPANIC OR LATINO,2010
4,3041,26749,Management occupations_Male,47016,19713,8523,WHITE ALONE NOT HISPANIC OR LATINO,2010
5,1283,11296,Business and financial operations occupations_...,34305,8830,3956,WHITE ALONE NOT HISPANIC OR LATINO,2010
6,1366,19720,"Computer, engineering, and science occupations...",21013,8213,4959,WHITE ALONE NOT HISPANIC OR LATINO,2010
7,467,12842,Computer and mathematical occupations_Male,12917,4808,2857,WHITE ALONE NOT HISPANIC OR LATINO,2010
8,444,4978,Architecture and engineering occupations_Male,4228,2627,1779,WHITE ALONE NOT HISPANIC OR LATINO,2010
9,455,1900,"Life, physical, and social science occupations...",3868,778,323,WHITE ALONE NOT HISPANIC OR LATINO,2010
10,4973,44266,"Education, legal, community service, arts, and...",68552,19359,4606,WHITE ALONE NOT HISPANIC OR LATINO,2010
11,388,4130,Community and social service occupations_Male,2586,1927,487,WHITE ALONE NOT HISPANIC OR LATINO,2010
12,810,7538,Legal occupations_Male,19210,2745,1069,WHITE ALONE NOT HISPANIC OR LATINO,2010
13,2123,14461,"Education, training, and library occupations_Male",18515,7680,1999,WHITE ALONE NOT HISPANIC OR LATINO,2010
14,1652,18137,"Arts, design, entertainment, sports, and media...",28241,7007,1051,WHITE ALONE NOT HISPANIC OR LATINO,2010
15,1086,5813,Healthcare practitioners and technical occupat...,9662,4149,2982,WHITE ALONE NOT HISPANIC OR LATINO,2010
16,569,4355,Health diagnosing and treating practitioners a...,9172,2867,2385,WHITE ALONE NOT HISPANIC OR LATINO,2010
17,517,1458,Health technologists and technicians_Male,490,1282,597,WHITE ALONE NOT HISPANIC OR LATINO,2010
18,6281,22270,Service occupations:_Male,14641,24975,11755,WHITE ALONE NOT HISPANIC OR LATINO,2010
19,106,1371,Healthcare support occupations_Male,379,635,221,WHITE ALONE NOT HISPANIC OR LATINO,2010
20,1791,5045,Protective service occupations:_Male,1751,7559,6346,WHITE ALONE NOT HISPANIC OR LATINO,2010
21,1399,2628,"Fire fighting and prevention, and other protec...",908,4578,3437,WHITE ALONE NOT HISPANIC OR LATINO,2010
22,392,2417,Law enforcement workers including supervisors_...,843,2981,2909,WHITE ALONE NOT HISPANIC OR LATINO,2010
23,1165,8041,Food preparation and serving related occupatio...,5953,6727,1957,WHITE ALONE NOT HISPANIC OR LATINO,2010
24,2324,5155,Building and grounds cleaning and maintenance ...,1967,5671,2075,WHITE ALONE NOT HISPANIC OR LATINO,2010
25,895,2658,Personal care and service occupations_Male,4591,4383,1156,WHITE ALONE NOT HISPANIC OR LATINO,2010
26,6073,42374,Sales and office occupations:_Male,41031,29723,11723,WHITE ALONE NOT HISPANIC OR LATINO,2010
27,2826,24553,Sales and related occupations_Male,31138,17938,6136,WHITE ALONE NOT HISPANIC OR LATINO,2010
28,3247,17821,Office and administrative support occupations_...,9893,11785,5587,WHITE ALONE NOT HISPANIC OR LATINO,2010
29,4313,21999,"Natural resources, construction, and maintenan...",3435,21606,12195,WHITE ALONE NOT HISPANIC OR LATINO,2010
...,...,...,...,...,...,...,...,...
43,189,5394,Computer and mathematical occupations_Female,7947,2199,1334,WHITE ALONE NOT HISPANIC OR LATINO,2019
44,323,2256,Architecture and engineering occupations_Female,2571,489,327,WHITE ALONE NOT HISPANIC OR LATINO,2019
45,289,3822,"Life, physical, and social science occupations...",5600,965,462,WHITE ALONE NOT HISPANIC OR LATINO,2019
46,5266,70592,"Education, legal, community service, arts, and...",69996,32083,17593,WHITE ALONE NOT HISPANIC OR LATINO,2019
47,436,7041,Community and social service occupations_Female,4631,2063,1976,WHITE ALONE NOT HISPANIC OR LATINO,2019
48,233,8109,Legal occupations_Female,11902,3947,1910,WHITE ALONE NOT HISPANIC OR LATINO,2019
49,3243,30605,"Educational instruction, and library occupatio...",23870,19735,12005,WHITE ALONE NOT HISPANIC OR LATINO,2019
50,1354,24837,"Arts, design, entertainment, sports, and media...",29593,6338,1702,WHITE ALONE NOT HISPANIC OR LATINO,2019
51,2059,16264,Healthcare practitioners and technical occupat...,16649,12007,7458,WHITE ALONE NOT HISPANIC OR LATINO,2019
52,1874,13361,Health diagnosing and treating practitioners a...,15881,9767,5883,WHITE ALONE NOT HISPANIC OR LATINO,2019
53,185,2903,Health technologists and technicians_Female,768,2240,1575,WHITE ALONE NOT HISPANIC OR LATINO,2019
54,3954,32104,Service occupations:_Female,16845,20776,9313,WHITE ALONE NOT HISPANIC OR LATINO,2019
55,680,12744,Healthcare support occupations_Female,1362,6560,3257,WHITE ALONE NOT HISPANIC OR LATINO,2019
56,214,1136,Protective service occupations:_Female,1879,1436,1771,WHITE ALONE NOT HISPANIC OR LATINO,2019
57,59,733,"Firefighting and prevention, and other protect...",1879,823,903,WHITE ALONE NOT HISPANIC OR LATINO,2019
58,155,403,Law enforcement workers including supervisors_...,0,613,868,WHITE ALONE NOT HISPANIC OR LATINO,2019
59,977,7389,Food preparation and serving related occupatio...,3929,5203,2550,WHITE ALONE NOT HISPANIC OR LATINO,2019
60,1044,1664,Building and grounds cleaning and maintenance ...,1348,3094,512,WHITE ALONE NOT HISPANIC OR LATINO,2019
61,1039,9171,Personal care and service occupations_Female,8327,4483,1223,WHITE ALONE NOT HISPANIC OR LATINO,2019
62,5182,47467,Sales and office occupations:_Female,42811,30843,17541,WHITE ALONE NOT HISPANIC OR LATINO,2019
63,1414,15472,Sales and related occupations_Female,24213,10014,5299,WHITE ALONE NOT HISPANIC OR LATINO,2019
64,3768,31995,Office and administrative support occupations_...,18598,20829,12242,WHITE ALONE NOT HISPANIC OR LATINO,2019
65,46,308,"Natural resources, construction, and maintenan...",514,342,627,WHITE ALONE NOT HISPANIC OR LATINO,2019
66,46,0,"Farming, fishing, and forestry occupations_Female",0,61,0,WHITE ALONE NOT HISPANIC OR LATINO,2019
67,0,187,Construction and extraction occupations_Female,497,209,142,WHITE ALONE NOT HISPANIC OR LATINO,2019
68,0,121,"Installation, maintenance, and repair occupati...",17,72,485,WHITE ALONE NOT HISPANIC OR LATINO,2019
69,674,3239,"Production, transportation, and material movin...",2190,3226,1124,WHITE ALONE NOT HISPANIC OR LATINO,2019
70,220,1995,Production occupations_Female,1075,1547,179,WHITE ALONE NOT HISPANIC OR LATINO,2019
71,285,587,Transportation occupations_Female,160,1181,294,WHITE ALONE NOT HISPANIC OR LATINO,2019
72,169,657,Material moving occupations_Female,955,498,651,WHITE ALONE NOT HISPANIC OR LATINO,2019

In [81]:
frames = [Asian_Alone, BLACK_OR_AFRICAN_AMERICAN_ALONE, HISPANIC_OR_LATINO, SomeOtherRaceAlone,Two_or_More_Races,
          White_Alone,WHITE_ALONE_NOT_HISPANIC_OR_LATINO]
race = pd.concat(frames)
race

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

,"Bronx County, New York","Kings County, New York",Label,"New York County, New York","Queens County, New York","Richmond County, New York",race,year
0,22160.0,121664,Total:,98647.0,248187,16530.0,Asian Alone,2010
1,12283.0,66638,Male:,44989.0,135390,8822.0,Asian Alone,2010
2,3201.0,15689,"Management, business, science, and arts occupa...",28593.0,41250,4012.0,Asian Alone,2010
3,1103.0,5399,"Management, business, and financial occupation...",12780.0,19782,1419.0,Asian Alone,2010
4,458.0,3330,Management occupations_Male,7144.0,11371,719.0,Asian Alone,2010
5,645.0,2069,Business and financial operations occupations_...,5636.0,8411,700.0,Asian Alone,2010
6,902.0,3650,"Computer, engineering, and science occupations...",5665.0,8594,820.0,Asian Alone,2010
7,544.0,2635,Computer and mathematical occupations_Male,3904.0,6097,472.0,Asian Alone,2010
8,271.0,872,Architecture and engineering occupations_Male,402.0,1773,298.0,Asian Alone,2010
9,87.0,143,"Life, physical, and social science occupations...",1359.0,724,50.0,Asian Alone,2010
10,525.0,4319,"Education, legal, community service, arts, and...",7061.0,6744,717.0,Asian Alone,2010
11,118.0,340,Community and social service occupations_Male,306.0,1405,0.0,Asian Alone,2010
12,0.0,395,Legal occupations_Male,2117.0,1199,69.0,Asian Alone,2010
13,407.0,1893,"Education, training, and library occupations_Male",1438.0,1700,462.0,Asian Alone,2010
14,0.0,1691,"Arts, design, entertainment, sports, and media...",3200.0,2440,186.0,Asian Alone,2010
15,671.0,2321,Healthcare practitioners and technical occupat...,3087.0,6130,1056.0,Asian Alone,2010
16,514.0,1775,Health diagnosing and treating practitioners a...,2746.0,4658,921.0,Asian Alone,2010
17,157.0,546,Health technologists and technicians_Male,341.0,1472,135.0,Asian Alone,2010
18,3083.0,18449,Service occupations:_Male,5275.0,24910,1681.0,Asian Alone,2010
19,48.0,755,Healthcare support occupations_Male,142.0,2581,370.0,Asian Alone,2010
20,798.0,908,Protective service occupations:_Male,219.0,3185,119.0,Asian Alone,2010
21,658.0,536,"Fire fighting and prevention, and other protec...",219.0,1831,119.0,Asian Alone,2010
22,140.0,372,Law enforcement workers including supervisors_...,0.0,1354,0.0,Asian Alone,2010
23,1472.0,14646,Food preparation and serving related occupatio...,3934.0,13650,952.0,Asian Alone,2010
24,533.0,1491,Building and grounds cleaning and maintenance ...,376.0,2458,50.0,Asian Alone,2010
25,232.0,649,Personal care and service occupations_Male,604.0,3036,190.0,Asian Alone,2010
26,2414.0,13445,Sales and office occupations:_Male,7763.0,32315,1109.0,Asian Alone,2010
27,1262.0,6869,Sales and related occupations_Male,5507.0,20826,573.0,Asian Alone,2010
28,1152.0,6576,Office and administrative support occupations_...,2256.0,11489,536.0,Asian Alone,2010
29,1711.0,6884,"Natural resources, construction, and maintenan...",1140.0,11516,1118.0,Asian Alone,2010
...,...,...,...,...,...,...,...,...
43,189.0,5394,Computer and mathematical occupations_Female,7947.0,2199,1334.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
44,323.0,2256,Architecture and engineering occupations_Female,2571.0,489,327.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
45,289.0,3822,"Life, physical, and social science occupations...",5600.0,965,462.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
46,5266.0,70592,"Education, legal, community service, arts, and...",69996.0,32083,17593.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
47,436.0,7041,Community and social service occupations_Female,4631.0,2063,1976.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
48,233.0,8109,Legal occupations_Female,11902.0,3947,1910.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
49,3243.0,30605,"Educational instruction, and library occupatio...",23870.0,19735,12005.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
50,1354.0,24837,"Arts, design, entertainment, sports, and media...",29593.0,6338,1702.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
51,2059.0,16264,Healthcare practitioners and technical occupat...,16649.0,12007,7458.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
52,1874.0,13361,Health diagnosing and treating practitioners a...,15881.0,9767,5883.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
53,185.0,2903,Health technologists and technicians_Female,768.0,2240,1575.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
54,3954.0,32104,Service occupations:_Female,16845.0,20776,9313.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
55,680.0,12744,Healthcare support occupations_Female,1362.0,6560,3257.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
56,214.0,1136,Protective service occupations:_Female,1879.0,1436,1771.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
57,59.0,733,"Firefighting and prevention, and other protect...",1879.0,823,903.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
58,155.0,403,Law enforcement workers including supervisors_...,0.0,613,868.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
59,977.0,7389,Food preparation and serving related occupatio...,3929.0,5203,2550.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
60,1044.0,1664,Building and grounds cleaning and maintenance ...,1348.0,3094,512.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
61,1039.0,9171,Personal care and service occupations_Female,8327.0,4483,1223.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
62,5182.0,47467,Sales and office occupations:_Female,42811.0,30843,17541.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
63,1414.0,15472,Sales and related occupations_Female,24213.0,10014,5299.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
64,3768.0,31995,Office and administrative support occupations_...,18598.0,20829,12242.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
65,46.0,308,"Natural resources, construction, and maintenan...",514.0,342,627.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
66,46.0,0,"Farming, fishing, and forestry occupations_Female",0.0,61,0.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
67,0.0,187,Construction and extraction occupations_Female,497.0,209,142.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
68,0.0,121,"Installation, maintenance, and repair occupati...",17.0,72,485.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
69,674.0,3239,"Production, transportation, and material movin...",2190.0,3226,1124.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
70,220.0,1995,Production occupations_Female,1075.0,1547,179.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
71,285.0,587,Transportation occupations_Female,160.0,1181,294.0,WHITE ALONE NOT HISPANIC OR LATINO,2019
72,169.0,657,Material moving occupations_Female,955.0,498,651.0,WHITE ALONE NOT HISPANIC OR LATINO,2019

In [82]:
race.to_csv(r"./race.csv")